*----------------------------------------------------------------------
c  author: Michael Kubocz
c  date  : 07.06.2006
c  modified: 05.10.07 (MK)
*----------------------------------------------------------------------

      integer PROCESS
************************* process parameters **************************

      logical squark_mix
      real*8 alpha,beta,sin_alpha,cos_alpha,sin_beta,cos_beta,
     &       sin_AB,cos_AB,tan2_W,
     &       sq_mix_theta,A_top,A_bottom,mu_param,
     &       mA,
     &       sin_thet,cos_thet,sin_theb,cos_theb

      real*8 cp_odd_mod,cp_even_mod
