# --- .deps/libggf_la-c_functions.Plo ---
c_functions.o libggf_la-c_functions.lo: \
 $(top_srcdir)/amplitudes/ggf/c_functions.F \
 $(top_srcdir)/amplitudes/ggf/c_functions.inc \
 $(top_srcdir)/amplitudes/ggf/c_coefficients.inc

$(top_srcdir)/amplitudes/ggf/c_functions.inc:

$(top_srcdir)/amplitudes/ggf/c_coefficients.inc:

# --- .deps/libggf_la-d_functions.Plo ---
d_functions.o libggf_la-d_functions.lo: \
 $(top_srcdir)/amplitudes/ggf/d_functions.F \
 $(top_srcdir)/amplitudes/ggf/d_functions.inc \
 $(top_srcdir)/amplitudes/ggf/c_coefficients.inc \
 $(top_srcdir)/amplitudes/ggf/d_coefficients.inc

$(top_srcdir)/amplitudes/ggf/d_functions.inc:

$(top_srcdir)/amplitudes/ggf/c_coefficients.inc:

$(top_srcdir)/amplitudes/ggf/d_coefficients.inc:

# --- .deps/libggf_la-gf_higgs_ME.Plo ---
gf_higgs_ME.o libggf_la-gf_higgs_ME.lo: \
 $(top_srcdir)/amplitudes/ggf/gf_higgs_ME.F \
 $(top_srcdir)/amplitudes/ggf/ggf_process.inc \
 $(top_srcdir)/amplitudes/ggf/ggf_dotproducts.inc

$(top_srcdir)/amplitudes/ggf/ggf_process.inc:

$(top_srcdir)/amplitudes/ggf/ggf_dotproducts.inc:

# --- .deps/libggf_la-ggf_amp_aux.Plo ---
ggf_amp_aux.o libggf_la-ggf_amp_aux.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_amp_aux.F \
 $(top_srcdir)/amplitudes/ggf/d_coefficients.inc \
 $(top_srcdir)/amplitudes/ggf/ggf_dotproducts.inc

$(top_srcdir)/amplitudes/ggf/d_coefficients.inc:

$(top_srcdir)/amplitudes/ggf/ggf_dotproducts.inc:

# --- .deps/libggf_la-ggf_Apen.Plo ---
ggf_Apen.o libggf_la-ggf_Apen.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_Apen.F \
 ../../include/VBFNLO/amplitudes/ggf/ggf_process.inc \
 ../../include/VBFNLO/amplitudes/ggf/d_coefficients.inc \
 ../../include/VBFNLO/amplitudes/ggf/ggf_dotproducts.inc

../../include/VBFNLO/amplitudes/ggf/ggf_process.inc:

../../include/VBFNLO/amplitudes/ggf/d_coefficients.inc:

../../include/VBFNLO/amplitudes/ggf/ggf_dotproducts.inc:

# --- .deps/libggf_la-ggf_dotproducts.Plo ---
ggf_dotproducts.o libggf_la-ggf_dotproducts.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_dotproducts.F \
 $(top_srcdir)/amplitudes/ggf/ggf_process.inc \
 $(top_srcdir)/amplitudes/ggf/ggf_dotproducts.inc

$(top_srcdir)/amplitudes/ggf/ggf_process.inc:

$(top_srcdir)/amplitudes/ggf/ggf_dotproducts.inc:

# --- .deps/libggf_la-ggf_Hpen_a.Plo ---
ggf_Hpen_a.o libggf_la-ggf_Hpen_a.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_Hpen_a.F

# --- .deps/libggf_la-ggf_Hpen_b.Plo ---
ggf_Hpen_b.o libggf_la-ggf_Hpen_b.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_Hpen_b.F

# --- .deps/libggf_la-ggf_Hpen_c.Plo ---
ggf_Hpen_c.o libggf_la-ggf_Hpen_c.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_Hpen_c.F

# --- .deps/libggf_la-ggf_Hpen.Plo ---
ggf_Hpen.o libggf_la-ggf_Hpen.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_Hpen.F \
 ../../include/VBFNLO/amplitudes/ggf/ggf_process.inc \
 ../../include/VBFNLO/amplitudes/ggf/d_coefficients.inc \
 ../../include/VBFNLO/amplitudes/ggf/ggf_dotproducts.inc

../../include/VBFNLO/amplitudes/ggf/ggf_process.inc:

../../include/VBFNLO/amplitudes/ggf/d_coefficients.inc:

../../include/VBFNLO/amplitudes/ggf/ggf_dotproducts.inc:

# --- .deps/libggf_la-ggf_tri_box.Plo ---
ggf_tri_box.o libggf_la-ggf_tri_box.lo: \
 $(top_srcdir)/amplitudes/ggf/ggf_tri_box.F \
 $(top_srcdir)/amplitudes/ggf/d_coefficients.inc

$(top_srcdir)/amplitudes/ggf/d_coefficients.inc:

# --- .deps/libggf_la-m2s_ggfh.Plo ---
m2s_ggfh.o libggf_la-m2s_ggfh.lo: \
 $(top_srcdir)/amplitudes/ggf/m2s_ggfh.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/ggf/ggf_process.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/process.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/ggf/ggf_process.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/process.inc:

