# --- .deps/libVBFNLOPDFsets_la-CT10Pdf.Plo ---
CT10Pdf.o libVBFNLOPDFsets_la-CT10Pdf.lo: \
 $(top_srcdir)/PDFsets/CT10Pdf.F

# --- .deps/libVBFNLOPDFsets_la-Ctq6Pdf.Plo ---
Ctq6Pdf.o libVBFNLOPDFsets_la-Ctq6Pdf.lo: \
 $(top_srcdir)/PDFsets/Ctq6Pdf.F

# --- .deps/libVBFNLOPDFsets_la-mrst2004qed.Plo ---
mrst2004qed.o libVBFNLOPDFsets_la-mrst2004qed.lo: \
 $(top_srcdir)/PDFsets/mrst2004qed.F

# --- .deps/libVBFNLOPDFsets_la-mstw2008.Plo ---
mstw2008.o libVBFNLOPDFsets_la-mstw2008.lo: \
 $(top_srcdir)/PDFsets/mstw2008.F

# --- .deps/libVBFNLOPDFsets_la-pftopdg.Plo ---
pftopdg.o libVBFNLOPDFsets_la-pftopdg.lo: \
 $(top_srcdir)/PDFsets/pftopdg.F

