#!/bin/bash

ALLDIRS=`make printalldirs`

echo "Putting grids into folder subdirectory grids..."

wdir=$PWD

griddir=${wdir}/grids
if test -e $griddir; then
  echo "Directory grids already exists. Exiting!"
  exit
fi
mkdir $griddir

tardir=${wdir}/grid-tars
if test -e $tardir; then
  echo "Directory grids-tars already exists. Exiting!"
  exit
fi
mkdir $tardir

for process in $ALLDIRS
do

  cd ${wdir}/${process}
  mkdir ${griddir}/${process}

  ls -l ./[gG][rR][iI][dD]* > /dev/null 2>&1
  if test $? -eq 0 && test `ls -l check*.o* | wc -l` -eq 1; then

    echo "Processing $process..."
  
    LO_iterations=`cat check*.o* | grep " LO_ITERATIONS"  | awk '{print $3}'`
    NLO_iterations=`cat check*.o* | grep " NLO_ITERATIONS" | awk '{print $3}'`
    
    for i in grid2_*.out.$LO_iterations; do
      if test -f $i; then
        cp $i ${griddir}/${process}/${i%.out.$LO_iterations}
      fi
    done
    for i in grid5_*.out.$LO_iterations; do
      if test -f $i; then
        cp $i ${griddir}/${process}/${i%.out.$LO_iterations}
      fi
    done
    for i in grid3_*.out.$NLO_iterations; do
      if test -f $i; then
        cp $i ${griddir}/${process}/${i%.out.$NLO_iterations}
      fi
    done
    for i in grid4_*.out.$NLO_iterations; do
      if test -f $i; then
        cp $i ${griddir}/${process}/${i%.out.$NLO_iterations}
      fi
    done

    ls -l ./GRID* > /dev/null 2>&1
    if test $? -eq 0; then
      cd GRID
      for i in grid2_*.out.$LO_iterations; do
        if test -f $i; then
          cp $i ${griddir}/${process}/${i%.out.$LO_iterations}
        fi
      done
      for i in grid5_*.out.$LO_iterations; do
        if test -f $i; then
          cp $i ${griddir}/${process}/${i%.out.$LO_iterations}
        fi
      done
      for i in grid3_*.out.$NLO_iterations; do
        if test -f $i; then
          cp $i ${griddir}/${process}/${i%.out.$NLO_iterations}
        fi
      done
      for i in grid4_*.out.$NLO_iterations; do
        if test -f $i; then
          cp $i ${griddir}/${process}/${i%.out.$NLO_iterations}
        fi
      done
    fi
    
    cd ${griddir}/${process}
    tar --group=root --owner=root --mode='a+rX' -cvf grid_${process}.tar grid*
    mv grid_${process}.tar ${tardir}

  else

    echo "No grids found or more than one run in directory for process $process."

  fi

done;

echo "Creating archive of all grids..."
cd $griddir
tar --group=root --owner=root --mode='a+rX' -cvf grids_all.tar *
mv grids_all.tar $tardir

cd $wdir

echo "Done."
  

