# --- .deps/libVBFNLOPhasespace_la-phasespace.Plo ---
phasespace.o libVBFNLOPhasespace_la-phasespace.lo: \
 $(top_srcdir)/phasespace/phasespace.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/process.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/process.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_ggf.Plo ---
ps_ggf.o libVBFNLOPhasespace_la-ps_ggf.lo: \
 $(top_srcdir)/phasespace/ps_ggf.F

# --- .deps/libVBFNLOPhasespace_la-ps_qqAAAj.Plo ---
ps_qqAAAj.o libVBFNLOPhasespace_la-ps_qqAAAj.lo: \
 $(top_srcdir)/phasespace/ps_qqAAAj.F \
 ../include/VBFNLO/utilities//global.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities//global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqAAj.Plo ---
ps_qqAAj.o libVBFNLOPhasespace_la-ps_qqAAj.lo: \
 $(top_srcdir)/phasespace/ps_qqAAj.F \
 ../include/VBFNLO/utilities//global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/global.inc ../include/globalvars.mod

../include/VBFNLO/utilities//global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/global.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqHHj.Plo ---
ps_qqHHj.o libVBFNLOPhasespace_la-ps_qqHHj.lo: \
 $(top_srcdir)/phasespace/ps_qqHHj.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/process.inc

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/process.inc:

# --- .deps/libVBFNLOPhasespace_la-ps_qqVAAj.Plo ---
ps_qqVAAj.o libVBFNLOPhasespace_la-ps_qqVAAj.lo: \
 $(top_srcdir)/phasespace/ps_qqVAAj.F \
 ../include/VBFNLO/utilities//global.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities//global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqVAj.Plo ---
ps_qqVAj.o libVBFNLOPhasespace_la-ps_qqVAj.lo: \
 $(top_srcdir)/phasespace/ps_qqVAj.F \
 ../include/VBFNLO/utilities//global.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities//global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqVHj.Plo ---
ps_qqVHj.o libVBFNLOPhasespace_la-ps_qqVHj.lo: \
 $(top_srcdir)/phasespace/ps_qqVHj.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/process.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/process.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqVj.Plo ---
ps_qqVj.o libVBFNLOPhasespace_la-ps_qqVj.lo: \
 $(top_srcdir)/phasespace/ps_qqVj.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/process.inc \
 ../include/VBFNLO/utilities//global.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/process.inc:

../include/VBFNLO/utilities//global.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqVVAj.Plo ---
ps_qqVVAj.o libVBFNLOPhasespace_la-ps_qqVVAj.lo: \
 $(top_srcdir)/phasespace/ps_qqVVAj.F \
 ../include/VBFNLO/utilities//global.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities//global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqVVj.Plo ---
ps_qqVVj.o libVBFNLOPhasespace_la-ps_qqVVj.lo: \
 $(top_srcdir)/phasespace/ps_qqVVj.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/process.inc \
 ../include/VBFNLO/utilities//global.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/process.inc:

../include/VBFNLO/utilities//global.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqVVVj.Plo ---
ps_qqVVVj.o libVBFNLOPhasespace_la-ps_qqVVVj.lo: \
 $(top_srcdir)/phasespace/ps_qqVVVj.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_qqWZ.Plo ---
ps_qqWZ.o libVBFNLOPhasespace_la-ps_qqWZ.lo: \
 $(top_srcdir)/phasespace/ps_qqWZ.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/process.inc \
 ../include/VBFNLO/utilities/coupl.inc \
 ../include/VBFNLO/utilities/kkcoupl.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/process.inc:

../include/VBFNLO/utilities/coupl.inc:

../include/VBFNLO/utilities/kkcoupl.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_tools.Plo ---
ps_tools.o libVBFNLOPhasespace_la-ps_tools.lo: \
 $(top_srcdir)/phasespace/ps_tools.F \
 ../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/phasespace/multires.inc

../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/phasespace/multires.inc:

# --- .deps/libVBFNLOPhasespace_la-ps_tribos_kk.Plo ---
ps_tribos_kk.o libVBFNLOPhasespace_la-ps_tribos_kk.lo: \
 $(top_srcdir)/phasespace/ps_tribos_kk.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/kkcoupl.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/kkcoupl.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_vnj.Plo ---
ps_vnj.o libVBFNLOPhasespace_la-ps_vnj.lo: \
 $(top_srcdir)/phasespace/ps_vnj.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/spin2coupl.inc \
 ../include/VBFNLO/utilities/process.inc \
 ../include/VBFNLO/utilities//global.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/spin2coupl.inc:

../include/VBFNLO/utilities/process.inc:

../include/VBFNLO/utilities//global.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_vvnj.Plo ---
ps_vvnj.o libVBFNLOPhasespace_la-ps_vvnj.lo: \
 $(top_srcdir)/phasespace/ps_vvnj.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/cuts.inc \
 ../include/VBFNLO/utilities/spin2coupl.inc \
 ../include/VBFNLO/utilities/process.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/VBFNLO/utilities/spin2coupl.inc:

../include/VBFNLO/utilities/process.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_WWW.Plo ---
ps_WWW.o libVBFNLOPhasespace_la-ps_WWW.lo: \
 $(top_srcdir)/phasespace/ps_WWW.F \
 ../include/VBFNLO/utilities//global.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities//global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

# --- .deps/libVBFNLOPhasespace_la-ps_ZZZj.Plo ---
ps_ZZZj.o libVBFNLOPhasespace_la-ps_ZZZj.lo: \
 $(top_srcdir)/phasespace/ps_ZZZj.F \
 ../include/VBFNLO/utilities//global.inc \
 ../include/VBFNLO/utilities/cuts.inc ../include/globalvars.mod

../include/VBFNLO/utilities//global.inc:

../include/VBFNLO/utilities/cuts.inc:

../include/globalvars.mod:

