# --- .deps/libIntegrals_la-A0.Plo ---
A0.o libIntegrals_la-A0.lo: \
 $(top_srcdir)/loops/Integrals/A0.F

# --- .deps/libIntegrals_la-Aux_Functions.Plo ---
Aux_Functions.o libIntegrals_la-Aux_Functions.lo: \
 $(top_srcdir)/loops/Integrals/Aux_Functions.F

# --- .deps/libIntegrals_la-B0C0D01MASG.Plo ---
B0C0D01MASG.o libIntegrals_la-B0C0D01MASG.lo: \
 $(top_srcdir)/loops/Integrals/B0C0D01MASG.F

# --- .deps/libIntegrals_la-B0C0D01MASG_QUAD.Plo ---
B0C0D01MASG_QUAD.o libIntegrals_la-B0C0D01MASG_QUAD.lo: \
 $(top_srcdir)/loops/Integrals/B0C0D01MASG_QUAD.F

# --- .deps/libIntegrals_la-B0functions.Plo ---
B0functions.o libIntegrals_la-B0functions.lo: \
 $(top_srcdir)/loops/Integrals/B0functions.F

# --- .deps/libIntegrals_la-B0QUAD.Plo ---
B0QUAD.o libIntegrals_la-B0QUAD.lo: \
 $(top_srcdir)/loops/Integrals/B0QUAD.F

# --- .deps/libIntegrals_la-C0functions.Plo ---
C0functions.o libIntegrals_la-C0functions.lo: \
 $(top_srcdir)/loops/Integrals/C0functions.F

# --- .deps/libIntegrals_la-C0QUAD.Plo ---
C0QUAD.o libIntegrals_la-C0QUAD.lo: \
 $(top_srcdir)/loops/Integrals/C0QUAD.F

# --- .deps/libIntegrals_la-cdilog.Plo ---
cdilog.o libIntegrals_la-cdilog.lo: \
 $(top_srcdir)/loops/Integrals/cdilog.F

# --- .deps/libIntegrals_la-D04QUAD.Plo ---
D04QUAD.o libIntegrals_la-D04QUAD.lo: \
 $(top_srcdir)/loops/Integrals/D04QUAD.F

# --- .deps/libIntegrals_la-D0functionsDiv.Plo ---
D0functionsDiv.o libIntegrals_la-D0functionsDiv.lo: \
 $(top_srcdir)/loops/Integrals/D0functionsDiv.F

# --- .deps/libIntegrals_la-D0functions.Plo ---
D0functions.o libIntegrals_la-D0functions.lo: \
 $(top_srcdir)/loops/Integrals/D0functions.F

# --- .deps/libIntegrals_la-D0QUAD.Plo ---
D0QUAD.o libIntegrals_la-D0QUAD.lo: \
 $(top_srcdir)/loops/Integrals/D0QUAD.F

# --- .deps/libIntegrals_la-dilog.Plo ---
dilog.o libIntegrals_la-dilog.lo: \
 $(top_srcdir)/loops/Integrals/dilog.F

# --- .deps/libIntegrals_la-E0functions.Plo ---
E0functions.o libIntegrals_la-E0functions.lo: \
 $(top_srcdir)/loops/Integrals/E0functions.F

# --- .deps/libIntegrals_la-E0QUAD.Plo ---
E0QUAD.o libIntegrals_la-E0QUAD.lo: \
 $(top_srcdir)/loops/Integrals/E0QUAD.F

# --- .deps/libIntegrals_la-F0.Plo ---
F0.o libIntegrals_la-F0.lo: \
 $(top_srcdir)/loops/Integrals/F0.F

# --- .deps/libIntegrals_la-F0_QUAD.Plo ---
F0_QUAD.o libIntegrals_la-F0_QUAD.lo: \
 $(top_srcdir)/loops/Integrals/F0_QUAD.F

# --- .deps/libIntegrals_la-QUAD_poly_Re.Plo ---
QUAD_poly_Re.o libIntegrals_la-QUAD_poly_Re.lo: \
 $(top_srcdir)/loops/Integrals/QUAD_poly_Re.F

# --- .deps/libIntegrals_la-scalarints.Plo ---
scalarints.o libIntegrals_la-scalarints.lo: \
 $(top_srcdir)/loops/Integrals/scalarints.F

