# --- .deps/libdiboson_la-AAtoaa.Plo ---
AAtoaa.o libdiboson_la-AAtoaa.lo: \
 $(top_srcdir)/amplitudes/diboson/AAtoaa.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSjwtowh_anomal.Plo ---
DIBOSjwtowh_anomal.o libdiboson_la-DIBOSjwtowh_anomal.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSjwtowh_anomal.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSjwtowh.Plo ---
DIBOSjwtowh.o libdiboson_la-DIBOSjwtowh.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSjwtowh.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOStoww_anomal.Plo ---
DIBOStoww_anomal.o libdiboson_la-DIBOStoww_anomal.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOStoww_anomal.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOStoww_had.Plo ---
DIBOStoww_had.o libdiboson_la-DIBOStoww_had.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOStoww_had.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOStoww.Plo ---
DIBOStoww.o libdiboson_la-DIBOStoww.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOStoww.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSwtowa_anomal.Plo ---
DIBOSwtowa_anomal.o libdiboson_la-DIBOSwtowa_anomal.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSwtowa_anomal.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSwtowa.Plo ---
DIBOSwtowa.o libdiboson_la-DIBOSwtowa.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSwtowa.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSwtowh_anomal.Plo ---
DIBOSwtowh_anomal.o libdiboson_la-DIBOSwtowh_anomal.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSwtowh_anomal.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSwtowh.Plo ---
DIBOSwtowh.o libdiboson_la-DIBOSwtowh.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSwtowh.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSwtowz_anomal.Plo ---
DIBOSwtowz_anomal.o libdiboson_la-DIBOSwtowz_anomal.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSwtowz_anomal.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSwtowz_had.Plo ---
DIBOSwtowz_had.o libdiboson_la-DIBOSwtowz_had.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSwtowz_had.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-DIBOSwtowz.Plo ---
DIBOSwtowz.o libdiboson_la-DIBOSwtowz.lo: \
 $(top_srcdir)/amplitudes/diboson/DIBOSwtowz.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-fl_vvjj.Plo ---
fl_vvjj.o libdiboson_la-fl_vvjj.lo: \
 $(top_srcdir)/amplitudes/diboson/fl_vvjj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/process.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libdiboson_la-ggAA.Plo ---
ggAA.o libdiboson_la-ggAA.lo: \
 $(top_srcdir)/amplitudes/diboson/ggAA.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libdiboson_la-ggWW.Plo ---
ggWW.o libdiboson_la-ggWW.lo: \
 $(top_srcdir)/amplitudes/diboson/ggWW.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libdiboson_la-ggZA.Plo ---
ggZA.o libdiboson_la-ggZA.lo: \
 $(top_srcdir)/amplitudes/diboson/ggZA.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libdiboson_la-ggZZ.Plo ---
ggZZ.o libdiboson_la-ggZZ.lo: \
 $(top_srcdir)/amplitudes/diboson/ggZZ.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libdiboson_la-m2s_qqAAj.Plo ---
m2s_qqAAj.o libdiboson_la-m2s_qqAAj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqAAj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libdiboson_la-m2s_qqAA.Plo ---
m2s_qqAA.o libdiboson_la-m2s_qqAA.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqAA.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-m2s_qqVVj.Plo ---
m2s_qqVVj.o libdiboson_la-m2s_qqVVj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqVVj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/process.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libdiboson_la-m2s_qqVV.Plo ---
m2s_qqVV.o libdiboson_la-m2s_qqVV.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqVV.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-m2s_qqWAj.Plo ---
m2s_qqWAj.o libdiboson_la-m2s_qqWAj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWAj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libdiboson_la-m2s_qqWA.Plo ---
m2s_qqWA.o libdiboson_la-m2s_qqWA.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWA.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-m2s_qqWHj2.Plo ---
m2s_qqWHj2.o libdiboson_la-m2s_qqWHj2.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWHj2.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libdiboson_la-m2s_qqWHjj.Plo ---
m2s_qqWHjj.o libdiboson_la-m2s_qqWHjj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWHjj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-m2s_qqWHj.Plo ---
m2s_qqWHj.o libdiboson_la-m2s_qqWHj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWHj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libdiboson_la-m2s_qqWH.Plo ---
m2s_qqWH.o libdiboson_la-m2s_qqWH.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWH.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libdiboson_la-m2s_qqWZj.Plo ---
m2s_qqWZj.o libdiboson_la-m2s_qqWZj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWZj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libdiboson_la-m2s_qqWZ.Plo ---
m2s_qqWZ.o libdiboson_la-m2s_qqWZ.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqWZ.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/globalvars.mod ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libdiboson_la-m2s_qqZAj.Plo ---
m2s_qqZAj.o libdiboson_la-m2s_qqZAj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqZAj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libdiboson_la-m2s_qqZA.Plo ---
m2s_qqZA.o libdiboson_la-m2s_qqZA.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqZA.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-m2s_qqZZj.Plo ---
m2s_qqZZj.o libdiboson_la-m2s_qqZZj.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqZZj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libdiboson_la-m2s_qqZZ.Plo ---
m2s_qqZZ.o libdiboson_la-m2s_qqZZ.lo: \
 $(top_srcdir)/amplitudes/diboson/m2s_qqZZ.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-mg2_ddAAg.Plo ---
mg2_ddAAg.o libdiboson_la-mg2_ddAAg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddAAg.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddAA.Plo ---
mg2_ddAA.o libdiboson_la-mg2_ddAA.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddAA.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddwwg.Plo ---
mg2_ddwwg.o libdiboson_la-mg2_ddwwg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddwwg.F \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddww_had.Plo ---
mg2_ddww_had.o libdiboson_la-mg2_ddww_had.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddww_had.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/process.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libdiboson_la-mg2_ddww.Plo ---
mg2_ddww.o libdiboson_la-mg2_ddww.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddww.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddZAg.Plo ---
mg2_ddZAg.o libdiboson_la-mg2_ddZAg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddZAg.F \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddZA.Plo ---
mg2_ddZA.o libdiboson_la-mg2_ddZA.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddZA.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddZZg.Plo ---
mg2_ddZZg.o libdiboson_la-mg2_ddZZg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddZZg.F \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddZZ_had.Plo ---
mg2_ddZZ_had.o libdiboson_la-mg2_ddZZ_had.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddZZ_had.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_ddZZ.Plo ---
mg2_ddZZ.o libdiboson_la-mg2_ddZZ.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_ddZZ.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_duwag.Plo ---
mg2_duwag.o libdiboson_la-mg2_duwag.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_duwag.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_duwa.Plo ---
mg2_duwa.o libdiboson_la-mg2_duwa.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_duwa.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/genps.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-mg2_duwhg.Plo ---
mg2_duwhg.o libdiboson_la-mg2_duwhg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_duwhg.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_duwzg.Plo ---
mg2_duwzg.o libdiboson_la-mg2_duwzg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_duwzg.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_duwz.Plo ---
mg2_duwz.o libdiboson_la-mg2_duwz.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_duwz.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

# --- .deps/libdiboson_la-mg2_udwag.Plo ---
mg2_udwag.o libdiboson_la-mg2_udwag.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwag.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_udwa.Plo ---
mg2_udwa.o libdiboson_la-mg2_udwa.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwa.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/genps.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-mg2_udWHdd.Plo ---
mg2_udWHdd.o libdiboson_la-mg2_udWHdd.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udWHdd.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_udWHgg.Plo ---
mg2_udWHgg.o libdiboson_la-mg2_udWHgg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udWHgg.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_udwhg.Plo ---
mg2_udwhg.o libdiboson_la-mg2_udwhg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwhg.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_udWHuu.Plo ---
mg2_udWHuu.o libdiboson_la-mg2_udWHuu.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udWHuu.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_udwmh.Plo ---
mg2_udwmh.o libdiboson_la-mg2_udwmh.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwmh.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-mg2_udwph.Plo ---
mg2_udwph.o libdiboson_la-mg2_udwph.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwph.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-mg2_udwzg.Plo ---
mg2_udwzg.o libdiboson_la-mg2_udwzg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwzg.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_udwz_had.Plo ---
mg2_udwz_had.o libdiboson_la-mg2_udwz_had.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwz_had.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

# --- .deps/libdiboson_la-mg2_udwz.Plo ---
mg2_udwz.o libdiboson_la-mg2_udwz.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_udwz.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/genps.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-mg2_uuAAg.Plo ---
mg2_uuAAg.o libdiboson_la-mg2_uuAAg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuAAg.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuAA.Plo ---
mg2_uuAA.o libdiboson_la-mg2_uuAA.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuAA.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuwwg.Plo ---
mg2_uuwwg.o libdiboson_la-mg2_uuwwg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuwwg.F \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuww_had.Plo ---
mg2_uuww_had.o libdiboson_la-mg2_uuww_had.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuww_had.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/process.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libdiboson_la-mg2_uuww.Plo ---
mg2_uuww.o libdiboson_la-mg2_uuww.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuww.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuZAg.Plo ---
mg2_uuZAg.o libdiboson_la-mg2_uuZAg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuZAg.F \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuZA.Plo ---
mg2_uuZA.o libdiboson_la-mg2_uuZA.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuZA.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuZZg.Plo ---
mg2_uuZZg.o libdiboson_la-mg2_uuZZg.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuZZg.F \
 $(top_srcdir)/amplitudes/diboson/genpsr.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genpsr.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuZZ_had.Plo ---
mg2_uuZZ_had.o libdiboson_la-mg2_uuZZ_had.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuZZ_had.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-mg2_uuZZ.Plo ---
mg2_uuZZ.o libdiboson_la-mg2_uuZZ.lo: \
 $(top_srcdir)/amplitudes/diboson/mg2_uuZZ.F \
 $(top_srcdir)/amplitudes/diboson/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/diboson/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqAAj.Plo ---
qqAAj.o libdiboson_la-qqAAj.lo: \
 $(top_srcdir)/amplitudes/diboson/qqAAj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqAA.Plo ---
qqAA.o libdiboson_la-qqAA.lo: \
 $(top_srcdir)/amplitudes/diboson/qqAA.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libdiboson_la-qqHWj_curr.Plo ---
qqHWj_curr.o libdiboson_la-qqHWj_curr.lo: \
 $(top_srcdir)/amplitudes/diboson/qqHWj_curr.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqVVj.Plo ---
qqVVj.o libdiboson_la-qqVVj.lo: \
 $(top_srcdir)/amplitudes/diboson/qqVVj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libdiboson_la-qqVV.Plo ---
qqVV.o libdiboson_la-qqVV.lo: \
 $(top_srcdir)/amplitudes/diboson/qqVV.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqWAj.Plo ---
qqWAj.o libdiboson_la-qqWAj.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWAj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqWA.Plo ---
qqWA.o libdiboson_la-qqWA.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWA.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqWHgg.Plo ---
qqWHgg.o libdiboson_la-qqWHgg.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWHgg.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-qqWHj2.Plo ---
qqWHj2.o libdiboson_la-qqWHj2.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWHj2.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

# --- .deps/libdiboson_la-qqWHj.Plo ---
qqWHj.o libdiboson_la-qqWHj.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWHj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqWH.Plo ---
qqWH.o libdiboson_la-qqWH.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWH.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

# --- .deps/libdiboson_la-qqWHqq.Plo ---
qqWHqq.o libdiboson_la-qqWHqq.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWHqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-qqWZj.Plo ---
qqWZj.o libdiboson_la-qqWZj.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWZj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libdiboson_la-qqWZ.Plo ---
qqWZ.o libdiboson_la-qqWZ.lo: \
 $(top_srcdir)/amplitudes/diboson/qqWZ.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

# --- .deps/libdiboson_la-qqZAj.Plo ---
qqZAj.o libdiboson_la-qqZAj.lo: \
 $(top_srcdir)/amplitudes/diboson/qqZAj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libdiboson_la-qqZA.Plo ---
qqZA.o libdiboson_la-qqZA.lo: \
 $(top_srcdir)/amplitudes/diboson/qqZA.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libdiboson_la-qqZZj.Plo ---
qqZZj.o libdiboson_la-qqZZj.lo: \
 $(top_srcdir)/amplitudes/diboson/qqZZj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libdiboson_la-qqZZ.Plo ---
qqZZ.o libdiboson_la-qqZZ.lo: \
 $(top_srcdir)/amplitudes/diboson/qqZZ.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libdiboson_la-vv_amp_aux.Plo ---
vv_amp_aux.o libdiboson_la-vv_amp_aux.lo: \
 $(top_srcdir)/amplitudes/diboson/vv_amp_aux.F \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libdiboson_la-ZAtoza.Plo ---
ZAtoza.o libdiboson_la-ZAtoza.lo: \
 $(top_srcdir)/amplitudes/diboson/ZAtoza.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-ZZtozz_had.Plo ---
ZZtozz_had.o libdiboson_la-ZZtozz_had.lo: \
 $(top_srcdir)/amplitudes/diboson/ZZtozz_had.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

# --- .deps/libdiboson_la-ZZtozz.Plo ---
ZZtozz.o libdiboson_la-ZZtozz.lo: \
 $(top_srcdir)/amplitudes/diboson/ZZtozz.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/diboson/tensor.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/diboson/tensor.inc:

