
c MB test for madgraph mhlm

	double precision gwwzp,mzp,mwp,wwp,wzp,gwwpz,gwwpzp,gwpwpzp,gwpwpz,gwwzpa
	double precision gwwzz, gwwaa, gwwza, gwzpwz,gwzpwa,gwzpwzp,gone,gwwww
	double complex GZpL(2),GZpN(2),GZpU(2),GZpD(2), GZpT(2)
	common /COUPL_KK_mgtest/ GZpL,GZpN,GZpU,GZpD,gwwzp,mzp,mwp,wwp,wzp,
     &				 gwwpz,gwwpzp,gwpwpzp,gwpwpz,gwwww,gwwzpa,
     &				 gwwzz,gwwza,gwwaa,gwzpwa,gwzpwzp,gwzpwz
					
	parameter (gone=0d0)
