# --- .deps/libvbf_la-gauge5-test-vv.Plo ---
gauge5-test-vv.o libvbf_la-gauge5-test-vv.lo: \
 $(top_srcdir)/amplitudes/vvjj/gauge5-test-vv.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/koppln.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/koppln.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-HAjj_currents.Plo ---
HAjj_currents.o libvbf_la-HAjj_currents.lo: \
 $(top_srcdir)/amplitudes/vvjj/HAjj_currents.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-HAjjj_ME.Plo ---
HAjjj_ME.o libvbf_la-HAjjj_ME.lo: \
 $(top_srcdir)/amplitudes/vvjj/HAjjj_ME.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-HAjj_ME.Plo ---
HAjj_ME.o libvbf_la-HAjj_ME.lo: \
 $(top_srcdir)/amplitudes/vvjj/HAjj_ME.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-jvirt5-isig.Plo ---
jvirt5-isig.o libvbf_la-jvirt5-isig.lo: \
 $(top_srcdir)/amplitudes/vvjj/jvirt5-isig.F

# --- .deps/libvbf_la-jvirt5.Plo ---
jvirt5.o libvbf_la-jvirt5.lo: \
 $(top_srcdir)/amplitudes/vvjj/jvirt5.F

# --- .deps/libvbf_la-m2s_qqHAqq.Plo ---
m2s_qqHAqq.o libvbf_la-m2s_qqHAqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/m2s_qqHAqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/Apdf.inc \
 ../../include/VBFNLO/utilities/mssm.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/Apdf.inc:

../../include/VBFNLO/utilities/mssm.inc:

# --- .deps/libvbf_la-m2s_qqWjqq.Plo ---
m2s_qqWjqq.o libvbf_la-m2s_qqWjqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/m2s_qqWjqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libvbf_la-m2s_qqWPPjqq.Plo ---
m2s_qqWPPjqq.o libvbf_la-m2s_qqWPPjqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/m2s_qqWPPjqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libvbf_la-m2s_qqwppqq.Plo ---
m2s_qqwppqq.o libvbf_la-m2s_qqwppqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/m2s_qqwppqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/tau_hel.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/tau_hel.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libvbf_la-m2s_qqwqq.Plo ---
m2s_qqwqq.o libvbf_la-m2s_qqwqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/m2s_qqwqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libvbf_la-m2s_qqZjqq.Plo ---
m2s_qqZjqq.o libvbf_la-m2s_qqZjqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/m2s_qqZjqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod \
 ../../include/vbfnlo_higgsto.mod ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

../../include/vbfnlo_higgsto.mod:

../../include/globalvars.mod:

# --- .deps/libvbf_la-m2s_qqzqq.Plo ---
m2s_qqzqq.o libvbf_la-m2s_qqzqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/m2s_qqzqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/tau_hel.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/Apdf.inc \
 ../../include/VBFNLO/utilities/mssm.inc ../../include/globalvars.mod \
 ../../include/vbfnlo_higgsto.mod ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/tau_hel.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/Apdf.inc:

../../include/VBFNLO/utilities/mssm.inc:

../../include/globalvars.mod:

../../include/vbfnlo_higgsto.mod:

../../include/globalvars.mod:

# --- .deps/libvbf_la-mg2_dsds.Plo ---
mg2_dsds.o libvbf_la-mg2_dsds.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_dsds.F \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-mg2_towpwp.Plo ---
mg2_towpwp.o libvbf_la-mg2_towpwp.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_towpwp.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-mg2_toww.Plo ---
mg2_toww.o libvbf_la-mg2_toww.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_toww.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

# --- .deps/libvbf_la-mg2_towz.Plo ---
mg2_towz.o libvbf_la-mg2_towz.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_towz.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

# --- .deps/libvbf_la-mg2_tozz.Plo ---
mg2_tozz.o libvbf_la-mg2_tozz.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_tozz.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

# --- .deps/libvbf_la-mg2_ucuc.Plo ---
mg2_ucuc.o libvbf_la-mg2_ucuc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_ucuc.F \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-mg2_usdc.Plo ---
mg2_usdc.o libvbf_la-mg2_usdc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_usdc.F \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-mg2_usus.Plo ---
mg2_usus.o libvbf_la-mg2_usus.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_usus.F \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-mg2_wma_ddsc.Plo ---
mg2_wma_ddsc.o libvbf_la-mg2_wma_ddsc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wma_ddsc.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_wma_ducc.Plo ---
mg2_wma_ducc.o libvbf_la-mg2_wma_ducc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wma_ducc.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_wma_duss.Plo ---
mg2_wma_duss.o libvbf_la-mg2_wma_duss.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wma_duss.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_wma_uusc.Plo ---
mg2_wma_uusc.o libvbf_la-mg2_wma_uusc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wma_uusc.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_wpa_ddcs.Plo ---
mg2_wpa_ddcs.o libvbf_la-mg2_wpa_ddcs.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wpa_ddcs.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_wpa_udcc.Plo ---
mg2_wpa_udcc.o libvbf_la-mg2_wpa_udcc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wpa_udcc.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_wpa_udss.Plo ---
mg2_wpa_udss.o libvbf_la-mg2_wpa_udss.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wpa_udss.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_wpa_uucs.Plo ---
mg2_wpa_uucs.o libvbf_la-mg2_wpa_uucs.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_wpa_uucs.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc \
 $(top_srcdir)/amplitudes/vvjj/genps.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

$(top_srcdir)/amplitudes/vvjj/genps.inc:

# --- .deps/libvbf_la-mg2_za_ucuc.Plo ---
mg2_za_ucuc.o libvbf_la-mg2_za_ucuc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_za_ucuc.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

# --- .deps/libvbf_la-mg2_za_udsc.Plo ---
mg2_za_udsc.o libvbf_la-mg2_za_udsc.lo: \
 $(top_srcdir)/amplitudes/vvjj/mg2_za_udsc.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-qqbqq.Plo ---
qqbqq.o libvbf_la-qqbqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqbqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqhhqqj.Plo ---
qqhhqqj.o libvbf_la-qqhhqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqhhqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorzn.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorzn.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqhhqq.Plo ---
qqhhqq.o libvbf_la-qqhhqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqhhqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorzn.inc \
 $(top_srcdir)/amplitudes/vvjj/tampz-lists.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorzn.inc:

$(top_srcdir)/amplitudes/vvjj/tampz-lists.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqhqqa.Plo ---
qqhqqa.o libvbf_la-qqhqqa.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqhqqa.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/koppln.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/koppln.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-qqhqq_pht.Plo ---
qqhqq_pht.o libvbf_la-qqhqq_pht.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqhqq_pht.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/mssm.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/mssm.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-qqhqq.Plo ---
qqhqq.o libvbf_la-qqhqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqhqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/koppln.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/mssm.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/koppln.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/mssm.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqsp2aaqqj.Plo ---
qqsp2aaqqj.o libvbf_la-qqsp2aaqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqsp2aaqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorzn.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorzn.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-qqsp2aaqq.Plo ---
qqsp2aaqq.o libvbf_la-qqsp2aaqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqsp2aaqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorzn.inc \
 $(top_srcdir)/amplitudes/vvjj/tampz-lists.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorzn.inc:

$(top_srcdir)/amplitudes/vvjj/tampz-lists.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-qqsp2wwqqj.Plo ---
qqsp2wwqqj.o libvbf_la-qqsp2wwqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqsp2wwqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/an_couplings.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/vvjj/tampr-lists.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/an_couplings.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/vvjj/tampr-lists.inc:

# --- .deps/libvbf_la-qqsp2wwqq.Plo ---
qqsp2wwqq.o libvbf_la-qqsp2wwqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqsp2wwqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/an_couplings.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/an_couplings.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-qqsp2zzqqj.Plo ---
qqsp2zzqqj.o libvbf_la-qqsp2zzqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqsp2zzqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-qqsp2zzqq.Plo ---
qqsp2zzqq.o libvbf_la-qqsp2zzqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqsp2zzqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 $(top_srcdir)/amplitudes/vvjj/tampz-lists.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

$(top_srcdir)/amplitudes/vvjj/tampz-lists.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libvbf_la-qqwmaqqj.Plo ---
qqwmaqqj.o libvbf_la-qqwmaqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwmaqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwmaqq.Plo ---
qqwmaqq.o libvbf_la-qqwmaqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwmaqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwmzqqj.Plo ---
qqwmzqqj.o libvbf_la-qqwmzqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwmzqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwmzqq.Plo ---
qqwmzqq.o libvbf_la-qqwmzqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwmzqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwpaqqj.Plo ---
qqwpaqqj.o libvbf_la-qqwpaqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwpaqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwpaqq.Plo ---
qqwpaqq.o libvbf_la-qqwpaqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwpaqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwppqqj.Plo ---
qqwppqqj.o libvbf_la-qqwppqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwppqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/vvjj/tampr_wpp_list.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/vvjj/tampr_wpp_list.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwppqq.Plo ---
qqwppqq.o libvbf_la-qqwppqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwppqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwpzqqj.Plo ---
qqwpzqqj.o libvbf_la-qqwpzqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwpzqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwpzqq.Plo ---
qqwpzqq.o libvbf_la-qqwpzqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwpzqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwwqqj.Plo ---
qqwwqqj.o libvbf_la-qqwwqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwwqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/an_couplings.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/vvjj/tampr-lists.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/an_couplings.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/vvjj/tampr-lists.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqwwqq.Plo ---
qqwwqq.o libvbf_la-qqwwqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqwwqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/an_couplings.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/an_couplings.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqzaqq.Plo ---
qqzaqq.o libvbf_la-qqzaqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqzaqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorzn.inc \
 $(top_srcdir)/amplitudes/vvjj/tampz-lists.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorzn.inc:

$(top_srcdir)/amplitudes/vvjj/tampz-lists.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqZWjqqi.Plo ---
qqZWjqqi.o libvbf_la-qqZWjqqi.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqZWjqqi.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqzzqqj.Plo ---
qqzzqqj.o libvbf_la-qqzzqqj.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqzzqqj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorzn.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorzn.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-qqzzqq.Plo ---
qqzzqq.o libvbf_la-qqzzqq.lo: \
 $(top_srcdir)/amplitudes/vvjj/qqzzqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorzn.inc \
 $(top_srcdir)/amplitudes/vvjj/tampz-lists.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/vvjj/tensorzn.inc:

$(top_srcdir)/amplitudes/vvjj/tampz-lists.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

# --- .deps/libvbf_la-spin2toaa.Plo ---
spin2toaa.o libvbf_la-spin2toaa.lo: \
 $(top_srcdir)/amplitudes/vvjj/spin2toaa.F \
 $(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorsp2aa.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-tbv.Plo ---
tbv.o libvbf_la-tbv.lo: \
 $(top_srcdir)/amplitudes/vvjj/tbv.F \
 ../../include/VBFNLO/utilities/koppln.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/an_couplings.inc

../../include/VBFNLO/utilities/koppln.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/an_couplings.inc:

# --- .deps/libvbf_la-tohh.Plo ---
tohh.o libvbf_la-tohh.lo: \
 $(top_srcdir)/amplitudes/vvjj/tohh.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-towa_anomal.Plo ---
towa_anomal.o libvbf_la-towa_anomal.lo: \
 $(top_srcdir)/amplitudes/vvjj/towa_anomal.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-towa.Plo ---
towa.o libvbf_la-towa.lo: \
 $(top_srcdir)/amplitudes/vvjj/towa.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-towpm_anomal.Plo ---
towpm_anomal.o libvbf_la-towpm_anomal.lo: \
 $(top_srcdir)/amplitudes/vvjj/towpm_anomal.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

# --- .deps/libvbf_la-towpm_had.Plo ---
towpm_had.o libvbf_la-towpm_had.lo: \
 $(top_srcdir)/amplitudes/vvjj/towpm_had.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

# --- .deps/libvbf_la-towpm.Plo ---
towpm.o libvbf_la-towpm.lo: \
 $(top_srcdir)/amplitudes/vvjj/towpm.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

# --- .deps/libvbf_la-toww_anomal2.Plo ---
toww_anomal2.o libvbf_la-toww_anomal2.lo: \
 $(top_srcdir)/amplitudes/vvjj/toww_anomal2.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-toww_had.Plo ---
toww_had.o libvbf_la-toww_had.lo: \
 $(top_srcdir)/amplitudes/vvjj/toww_had.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libvbf_la-toww_Hres.Plo ---
toww_Hres.o libvbf_la-toww_Hres.lo: \
 $(top_srcdir)/amplitudes/vvjj/toww_Hres.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-toww_kk.Plo ---
toww_kk.o libvbf_la-toww_kk.lo: \
 $(top_srcdir)/amplitudes/vvjj/toww_kk.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/kkcoupl.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/kkcoupl.inc:

# --- .deps/libvbf_la-toww.Plo ---
toww.o libvbf_la-toww.lo: \
 $(top_srcdir)/amplitudes/vvjj/toww.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-toww_spin2.Plo ---
toww_spin2.o libvbf_la-toww_spin2.lo: \
 $(top_srcdir)/amplitudes/vvjj/toww_spin2.F \
 $(top_srcdir)/amplitudes/vvjj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libvbf_la-towz_anomal.Plo ---
towz_anomal.o libvbf_la-towz_anomal.lo: \
 $(top_srcdir)/amplitudes/vvjj/towz_anomal.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-towz_had.Plo ---
towz_had.o libvbf_la-towz_had.lo: \
 $(top_srcdir)/amplitudes/vvjj/towz_had.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libvbf_la-towz_kk.Plo ---
towz_kk.o libvbf_la-towz_kk.lo: \
 $(top_srcdir)/amplitudes/vvjj/towz_kk.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/kkcoupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/kkcoupl.inc:

# --- .deps/libvbf_la-towz.Plo ---
towz.o libvbf_la-towz.lo: \
 $(top_srcdir)/amplitudes/vvjj/towz.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-towz_spin2.Plo ---
towz_spin2.o libvbf_la-towz_spin2.lo: \
 $(top_srcdir)/amplitudes/vvjj/towz_spin2.F \
 $(top_srcdir)/amplitudes/vvjj/tensorw.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorw.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libvbf_la-toza_anomal.Plo ---
toza_anomal.o libvbf_la-toza_anomal.lo: \
 $(top_srcdir)/amplitudes/vvjj/toza_anomal.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-toza.Plo ---
toza.o libvbf_la-toza.lo: \
 $(top_srcdir)/amplitudes/vvjj/toza.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-tozz_anomal.Plo ---
tozz_anomal.o libvbf_la-tozz_anomal.lo: \
 $(top_srcdir)/amplitudes/vvjj/tozz_anomal.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-tozz_had.Plo ---
tozz_had.o libvbf_la-tozz_had.lo: \
 $(top_srcdir)/amplitudes/vvjj/tozz_had.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl_haddecay.inc \
 ../../include/VBFNLO/utilities/process.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl_haddecay.inc:

../../include/VBFNLO/utilities/process.inc:

# --- .deps/libvbf_la-tozz_Hres.Plo ---
tozz_Hres.o libvbf_la-tozz_Hres.lo: \
 $(top_srcdir)/amplitudes/vvjj/tozz_Hres.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-tozz_kk.Plo ---
tozz_kk.o libvbf_la-tozz_kk.lo: \
 $(top_srcdir)/amplitudes/vvjj/tozz_kk.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/kkcoupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/kkcoupl.inc:

# --- .deps/libvbf_la-tozz.Plo ---
tozz.o libvbf_la-tozz.lo: \
 $(top_srcdir)/amplitudes/vvjj/tozz.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvbf_la-tozz_spin2.Plo ---
tozz_spin2.o libvbf_la-tozz_spin2.lo: \
 $(top_srcdir)/amplitudes/vvjj/tozz_spin2.F \
 $(top_srcdir)/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

$(top_srcdir)/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libvbf_la-VBF_BOX_ABE_CURRENT.Plo ---
VBF_BOX_ABE_CURRENT.o libvbf_la-VBF_BOX_ABE_CURRENT.lo: \
 $(top_srcdir)/amplitudes/vvjj/VBF_BOX_ABE_CURRENT.F

# --- .deps/libvbf_la-VBF_BOX_ABE.Plo ---
VBF_BOX_ABE.o libvbf_la-VBF_BOX_ABE.lo: \
 $(top_srcdir)/amplitudes/vvjj/VBF_BOX_ABE.F

# --- .deps/libvbf_la-VBF_PENT_ABE_CURRENT.Plo ---
VBF_PENT_ABE_CURRENT.o libvbf_la-VBF_PENT_ABE_CURRENT.lo: \
 $(top_srcdir)/amplitudes/vvjj/VBF_PENT_ABE_CURRENT.F

# --- .deps/libvbf_la-VBF_PENT_ABE.Plo ---
VBF_PENT_ABE.o libvbf_la-VBF_PENT_ABE.lo: \
 $(top_srcdir)/amplitudes/vvjj/VBF_PENT_ABE.F

# --- .deps/libvbf_la-vvjj_amp_aux.Plo ---
vvjj_amp_aux.o libvbf_la-vvjj_amp_aux.lo: \
 $(top_srcdir)/amplitudes/vvjj/vvjj_amp_aux.F

# --- .deps/libvbf_la-vvsp2tovv.Plo ---
vvsp2tovv.o libvbf_la-vvsp2tovv.lo: \
 $(top_srcdir)/amplitudes/vvjj/vvsp2tovv.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

