# --- .deps/libVBFNLOAmplitudes_la-amplitudes.Plo ---
amplitudes.o libVBFNLOAmplitudes_la-amplitudes.lo: \
 $(top_srcdir)/amplitudes/amplitudes.F \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/process.inc \
 ../include/VBFNLO/utilities/BLHAhelper.inc ../include/globalvars.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/process.inc:

../include/VBFNLO/utilities/BLHAhelper.inc:

../include/globalvars.mod:

