# --- .deps/libSpin2_la-aatxxx_sing.Plo ---
aatxxx_sing.o libSpin2_la-aatxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/aatxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-aatxxx_tripn.Plo ---
aatxxx_tripn.o libSpin2_la-aatxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/aatxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-aztxxx_sing.Plo ---
aztxxx_sing.o libSpin2_la-aztxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/aztxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-aztxxx_tripn.Plo ---
aztxxx_tripn.o libSpin2_la-aztxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/aztxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uaaxxx_sing.Plo ---
uaaxxx_sing.o libSpin2_la-uaaxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/uaaxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uaaxxx_tripn.Plo ---
uaaxxx_tripn.o libSpin2_la-uaaxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/uaaxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uazxxx_sing.Plo ---
uazxxx_sing.o libSpin2_la-uazxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/uazxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uazxxx_tripn.Plo ---
uazxxx_tripn.o libSpin2_la-uazxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/uazxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uwaxxx_trippm.Plo ---
uwaxxx_trippm.o libSpin2_la-uwaxxx_trippm.lo: \
 $(top_srcdir)/amplitudes/Spin2/uwaxxx_trippm.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uwwxxx_sing.Plo ---
uwwxxx_sing.o libSpin2_la-uwwxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/uwwxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uwwxxx_tripn.Plo ---
uwwxxx_tripn.o libSpin2_la-uwwxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/uwwxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uwzxxx_trippm.Plo ---
uwzxxx_trippm.o libSpin2_la-uwzxxx_trippm.lo: \
 $(top_srcdir)/amplitudes/Spin2/uwzxxx_trippm.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uzzxxx_sing.Plo ---
uzzxxx_sing.o libSpin2_la-uzzxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/uzzxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-uzzxxx_tripn.Plo ---
uzzxxx_tripn.o libSpin2_la-uzzxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/uzzxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-watxxx_trippm.Plo ---
watxxx_trippm.o libSpin2_la-watxxx_trippm.lo: \
 $(top_srcdir)/amplitudes/Spin2/watxxx_trippm.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-wwtxxx_sing.Plo ---
wwtxxx_sing.o libSpin2_la-wwtxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/wwtxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-wwtxxx_tripn.Plo ---
wwtxxx_tripn.o libSpin2_la-wwtxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/wwtxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-wztxxx_trippm.Plo ---
wztxxx_trippm.o libSpin2_la-wztxxx_trippm.lo: \
 $(top_srcdir)/amplitudes/Spin2/wztxxx_trippm.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-zztxxx_sing.Plo ---
zztxxx_sing.o libSpin2_la-zztxxx_sing.lo: \
 $(top_srcdir)/amplitudes/Spin2/zztxxx_sing.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

# --- .deps/libSpin2_la-zztxxx_tripn.Plo ---
zztxxx_tripn.o libSpin2_la-zztxxx_tripn.lo: \
 $(top_srcdir)/amplitudes/Spin2/zztxxx_tripn.F \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/spin2coupl.inc

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/spin2coupl.inc:

