# --- .deps/libTIB_la-tensor_redux_BijLUde1M_Div.Plo ---
tensor_redux_BijLUde1M_Div.o libTIB_la-tensor_redux_BijLUde1M_Div.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde1M_Div.F

# --- .deps/libTIB_la-tensor_redux_BijLUde1M.Plo ---
tensor_redux_BijLUde1M.o libTIB_la-tensor_redux_BijLUde1M.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde1M.F

# --- .deps/libTIB_la-tensor_redux_BijLUde_Div.Plo ---
tensor_redux_BijLUde_Div.o libTIB_la-tensor_redux_BijLUde_Div.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde_Div.F

# --- .deps/libTIB_la-tensor_redux_BijLUde_G_Div.Plo ---
tensor_redux_BijLUde_G_Div.o libTIB_la-tensor_redux_BijLUde_G_Div.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde_G_Div.F

# --- .deps/libTIB_la-tensor_redux_BijLUde_G.Plo ---
tensor_redux_BijLUde_G.o libTIB_la-tensor_redux_BijLUde_G.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde_G.F

# --- .deps/libTIB_la-tensor_redux_BijLUde.Plo ---
tensor_redux_BijLUde.o libTIB_la-tensor_redux_BijLUde.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde.F

# --- .deps/libTIB_la-tensor_redux_BijLUde_R3_G_Div.Plo ---
tensor_redux_BijLUde_R3_G_Div.o \
 libTIB_la-tensor_redux_BijLUde_R3_G_Div.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde_R3_G_Div.F

# --- .deps/libTIB_la-tensor_redux_BijLUde_R3_G.Plo ---
tensor_redux_BijLUde_R3_G.o libTIB_la-tensor_redux_BijLUde_R3_G.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde_R3_G.F

# --- .deps/libTIB_la-tensor_redux_BijLUde_R3_G_QUAD.Plo ---
tensor_redux_BijLUde_R3_G_QUAD.o \
 libTIB_la-tensor_redux_BijLUde_R3_G_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/B/tensor_redux_BijLUde_R3_G_QUAD.F

