# --- .deps/libUtilities_la-bra_ket_subroutines.Plo ---
bra_ket_subroutines.o libUtilities_la-bra_ket_subroutines.lo: \
 $(top_srcdir)/loops/Utilities/bra_ket_subroutines.F

# --- .deps/libUtilities_la-dotprod_QUAD.Plo ---
dotprod_QUAD.o libUtilities_la-dotprod_QUAD.lo: \
 $(top_srcdir)/loops/Utilities/dotprod_QUAD.F

# --- .deps/libUtilities_la-GaugeTest.Plo ---
GaugeTest.o libUtilities_la-GaugeTest.lo: \
 $(top_srcdir)/loops/Utilities/GaugeTest.F \
 $(top_srcdir)/loops/Utilities/GaugeTest.inc

$(top_srcdir)/loops/Utilities/GaugeTest.inc:

# --- .deps/libUtilities_la-GaugeTest_QUAD.Plo ---
GaugeTest_QUAD.o libUtilities_la-GaugeTest_QUAD.lo: \
 $(top_srcdir)/loops/Utilities/GaugeTest_QUAD.F \
 $(top_srcdir)/loops/Utilities/GaugeTest.inc

$(top_srcdir)/loops/Utilities/GaugeTest.inc:

# --- .deps/libUtilities_la-GluonSelf.Plo ---
GluonSelf.o libUtilities_la-GluonSelf.lo: \
 $(top_srcdir)/loops/Utilities/GluonSelf.F

# --- .deps/libUtilities_la-MatrixElements.Plo ---
MatrixElements.o libUtilities_la-MatrixElements.lo: \
 $(top_srcdir)/loops/Utilities/MatrixElements.F

# --- .deps/libUtilities_la-pent45_noAbe.Plo ---
pent45_noAbe.o libUtilities_la-pent45_noAbe.lo: \
 $(top_srcdir)/loops/Utilities/pent45_noAbe.F

# --- .deps/libUtilities_la-Pent_to_boxes.Plo ---
Pent_to_boxes.o libUtilities_la-Pent_to_boxes.lo: \
 $(top_srcdir)/loops/Utilities/Pent_to_boxes.F

# --- .deps/libUtilities_la-ten2cc.Plo ---
ten2cc.o libUtilities_la-ten2cc.lo: \
 $(top_srcdir)/loops/Utilities/ten2cc.F

# --- .deps/libUtilities_la-Utilities_QUAD.Plo ---
Utilities_QUAD.o libUtilities_la-Utilities_QUAD.lo: \
 $(top_srcdir)/loops/Utilities/Utilities_QUAD.F

# --- .deps/libUtilities_la-Wardtest.Plo ---
Wardtest.o libUtilities_la-Wardtest.lo: \
 $(top_srcdir)/loops/Utilities/Wardtest.F

