# --- .deps/libTIE_la-E0FunctionsG.Plo ---
E0FunctionsG.o libTIE_la-E0FunctionsG.lo: \
 $(top_srcdir)/loops/TenRed/E/E0FunctionsG.F

# --- .deps/libTIE_la-E0FunctionsG_QUAD.Plo ---
E0FunctionsG_QUAD.o libTIE_la-E0FunctionsG_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/E/E0FunctionsG_QUAD.F

# --- .deps/libTIE_la-tensor_redux_Eij_new_Re_Com_1Mas.Plo ---
tensor_redux_Eij_new_Re_Com_1Mas.o \
 libTIE_la-tensor_redux_Eij_new_Re_Com_1Mas.lo: \
 $(top_srcdir)/loops/TenRed/E/tensor_redux_Eij_new_Re_Com_1Mas.F

# --- .deps/libTIE_la-tensor_redux_Eij_new_Re_Com.Plo ---
tensor_redux_Eij_new_Re_Com.o libTIE_la-tensor_redux_Eij_new_Re_Com.lo: \
 $(top_srcdir)/loops/TenRed/E/tensor_redux_Eij_new_Re_Com.F

# --- .deps/libTIE_la-tensor_redux_Eij_new_Re_Com_QUAD.Plo ---
tensor_redux_Eij_new_Re_Com_QUAD.o \
 libTIE_la-tensor_redux_Eij_new_Re_Com_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/E/tensor_redux_Eij_new_Re_Com_QUAD.F

# --- .deps/libTIE_la-tensor_redux_Eij_new_Re_Com_R5_G_Div.Plo ---
tensor_redux_Eij_new_Re_Com_R5_G_Div.o \
 libTIE_la-tensor_redux_Eij_new_Re_Com_R5_G_Div.lo: \
 $(top_srcdir)/loops/TenRed/E/tensor_redux_Eij_new_Re_Com_R5_G_Div.F

# --- .deps/libTIE_la-tensor_redux_Eij_new_Re_Com_R5_G.Plo ---
tensor_redux_Eij_new_Re_Com_R5_G.o \
 libTIE_la-tensor_redux_Eij_new_Re_Com_R5_G.lo: \
 $(top_srcdir)/loops/TenRed/E/tensor_redux_Eij_new_Re_Com_R5_G.F

# --- .deps/libTIE_la-tensor_redux_Eij_new_Re_Com_R5_G_QUAD.Plo ---
tensor_redux_Eij_new_Re_Com_R5_G_QUAD.o \
 libTIE_la-tensor_redux_Eij_new_Re_Com_R5_G_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/E/tensor_redux_Eij_new_Re_Com_R5_G_QUAD.F

# --- .deps/libTIE_la-tensor_redux_Eij.Plo ---
tensor_redux_Eij.o libTIE_la-tensor_redux_Eij.lo: \
 $(top_srcdir)/loops/TenRed/E/tensor_redux_Eij.F

# --- .deps/libTIE_la-XEgetM1M3_Div.Plo ---
XEgetM1M3_Div.o libTIE_la-XEgetM1M3_Div.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetM1M3_Div.F

# --- .deps/libTIE_la-XEgetM1M3.Plo ---
XEgetM1M3.o libTIE_la-XEgetM1M3.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetM1M3.F

# --- .deps/libTIE_la-XEgetM1M3_QUAD.Plo ---
XEgetM1M3_QUAD.o libTIE_la-XEgetM1M3_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetM1M3_QUAD.F

# --- .deps/libTIE_la-XEgetM1M3Sim.Plo ---
XEgetM1M3Sim.o libTIE_la-XEgetM1M3Sim.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetM1M3Sim.F

# --- .deps/libTIE_la-XEgetOddM1M3_Div.Plo ---
XEgetOddM1M3_Div.o libTIE_la-XEgetOddM1M3_Div.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetOddM1M3_Div.F

# --- .deps/libTIE_la-XEgetOddM1M3.Plo ---
XEgetOddM1M3.o libTIE_la-XEgetOddM1M3.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetOddM1M3.F

# --- .deps/libTIE_la-XEgetOddSimM1M3.Plo ---
XEgetOddSimM1M3.o libTIE_la-XEgetOddSimM1M3.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetOddSimM1M3.F

# --- .deps/libTIE_la-XEgetOddSimM1M3_QUAD.Plo ---
XEgetOddSimM1M3_QUAD.o libTIE_la-XEgetOddSimM1M3_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/E/XEgetOddSimM1M3_QUAD.F

