# --- .deps/libqcdwz_la-m2s_WW2j.Plo ---
m2s_WW2j.o libqcdwz_la-m2s_WW2j.lo: \
 $(top_srcdir)/amplitudes/qcdwz/m2s_WW2j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/loops/Utilities/GaugeTest.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/loops/Utilities/GaugeTest.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libqcdwz_la-m2s_WW3j.Plo ---
m2s_WW3j.o libqcdwz_la-m2s_WW3j.lo: \
 $(top_srcdir)/amplitudes/qcdwz/m2s_WW3j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libqcdwz_la-m2s_WZ2j.Plo ---
m2s_WZ2j.o libqcdwz_la-m2s_WZ2j.lo: \
 $(top_srcdir)/amplitudes/qcdwz/m2s_WZ2j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/loops/Utilities/GaugeTest.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/process.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod ../../include/globalvars.mod \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/loops/Utilities/GaugeTest.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libqcdwz_la-m2s_WZ3j.Plo ---
m2s_WZ3j.o libqcdwz_la-m2s_WZ3j.lo: \
 $(top_srcdir)/amplitudes/qcdwz/m2s_WZ3j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/process.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libqcdwz_la-m2s_ZZ2j.Plo ---
m2s_ZZ2j.o libqcdwz_la-m2s_ZZ2j.lo: \
 $(top_srcdir)/amplitudes/qcdwz/m2s_ZZ2j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/cuts.inc \
 ../../include/VBFNLO/amplitudes/vvjj/tensorz.inc \
 ../../include/VBFNLO/loops/Utilities/GaugeTest.inc \
 $(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/cuts.inc:

../../include/VBFNLO/amplitudes/vvjj/tensorz.inc:

../../include/VBFNLO/loops/Utilities/GaugeTest.inc:

$(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libqcdwz_la-m2s_ZZ3j.Plo ---
m2s_ZZ3j.o libqcdwz_la-m2s_ZZ3j.lo: \
 $(top_srcdir)/amplitudes/qcdwz/m2s_ZZ3j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/amplitudes/vvjj/tensorz.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 $(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/amplitudes/vvjj/tensorz.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

$(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libqcdwz_la-nloStuff.Plo ---
nloStuff.o libqcdwz_la-nloStuff.lo: \
 $(top_srcdir)/amplitudes/qcdwz/nloStuff.F \
 $(top_srcdir)/amplitudes/qcdwz/brakets.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc

$(top_srcdir)/amplitudes/qcdwz/brakets.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libqcdwz_la-qqwwqqVirt.Plo ---
qqwwqqVirt.o libqcdwz_la-qqwwqqVirt.lo: \
 $(top_srcdir)/amplitudes/qcdwz/qqwwqqVirt.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

# --- .deps/libqcdwz_la-qqwzggVirt.Plo ---
qqwzggVirt.o libqcdwz_la-qqwzggVirt.lo: \
 $(top_srcdir)/amplitudes/qcdwz/qqwzggVirt.F \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

# --- .deps/libqcdwz_la-qqwzqqVirt.Plo ---
qqwzqqVirt.o libqcdwz_la-qqwzqqVirt.lo: \
 $(top_srcdir)/amplitudes/qcdwz/qqwzqqVirt.F \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

# --- .deps/libqcdwz_la-qqzzggVirt.Plo ---
qqzzggVirt.o libqcdwz_la-qqzzggVirt.lo: \
 $(top_srcdir)/amplitudes/qcdwz/qqzzggVirt.F \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libqcdwz_la-qqzzqqVirt.Plo ---
qqzzqqVirt.o libqcdwz_la-qqzzqqVirt.lo: \
 $(top_srcdir)/amplitudes/qcdwz/qqzzqqVirt.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/qcdwz/cacheZZ.inc:

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libqcdwz_la-ug2dgwz.Plo ---
ug2dgwz.o libqcdwz_la-ug2dgwz.lo: \
 $(top_srcdir)/amplitudes/qcdwz/ug2dgwz.F \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 $(top_srcdir)/amplitudes/qcdwz/brakets.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/globalvars.mod ../../include/globalvars.mod

$(top_srcdir)/amplitudes/qcdwz/common.inc:

$(top_srcdir)/amplitudes/qcdwz/brakets.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libqcdwz_la-uu2udwz.Plo ---
uu2udwz.o libqcdwz_la-uu2udwz.lo: \
 $(top_srcdir)/amplitudes/qcdwz/uu2udwz.F \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/qcdwz/brakets.inc \
 ../../include/globalvars.mod ../../include/globalvars.mod

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/qcdwz/brakets.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

# --- .deps/libqcdwz_la-Wjj.Plo ---
Wjj.o libqcdwz_la-Wjj.lo: \
 $(top_srcdir)/amplitudes/qcdwz/Wjj.F \
 $(top_srcdir)/amplitudes/qcdwz/common.inc \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/scales.inc ../../include/globalvars.mod \
 ../../include/globalvars.mod ../../include/globalvars.mod \
 ../../include/globalvars.mod ../../include/globalvars.mod \
 ../../include/globalvars.mod

$(top_srcdir)/amplitudes/qcdwz/common.inc:

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/globalvars.mod:

../../include/globalvars.mod:

../../include/globalvars.mod:

../../include/globalvars.mod:

../../include/globalvars.mod:

../../include/globalvars.mod:

