# --- .deps/libVBFNLO_la-vbfnlo_main.Plo ---
vbfnlo_main.o libVBFNLO_la-vbfnlo_main.lo ../include/vbfnlo_main.mod: \
 $(top_srcdir)/lib/vbfnlo_main.F90 \
 ../include/VBFNLO/utilities/global.inc \
 ../include/VBFNLO/utilities/lha.inc \
 ../include/VBFNLO/utilities/tau_hel.inc \
 ../include/VBFNLO/utilities/process.inc \
 ../include/VBFNLO/utilities/scales.inc \
 ../include/VBFNLO/utilities/global.inc ../include/monaco.mod \
 ../include/globalvars.mod ../include/vbfnloversion.mod \
 ../include/vbfnlo_mpi.mod ../include/globalvars.mod \
 ../include/stopwatch.mod ../include/vbfnlo_mpi.mod \
 ../include/globalvars.mod ../include/globalvars.mod \
 ../include/vbfnlo_mpi.mod ../include/vbfnlo_mpi.mod \
 ../include/stdoutredirect.mod ../include/vbfnlo_mpi.mod \
 ../include/vbfnlo_mpi.mod ../include/vbfnlo_mpi.mod

../include/VBFNLO/utilities/global.inc:

../include/VBFNLO/utilities/lha.inc:

../include/VBFNLO/utilities/tau_hel.inc:

../include/VBFNLO/utilities/process.inc:

../include/VBFNLO/utilities/scales.inc:

../include/VBFNLO/utilities/global.inc:

../include/monaco.mod:

../include/globalvars.mod:

../include/vbfnloversion.mod:

../include/vbfnlo_mpi.mod:

../include/globalvars.mod:

../include/stopwatch.mod:

../include/vbfnlo_mpi.mod:

../include/globalvars.mod:

../include/globalvars.mod:

../include/vbfnlo_mpi.mod:

../include/vbfnlo_mpi.mod:

../include/stdoutredirect.mod:

../include/vbfnlo_mpi.mod:

../include/vbfnlo_mpi.mod:

../include/vbfnlo_mpi.mod:

# --- .deps/trigger_cxx_linking.Plo ---
trigger_cxx_linking.lo: \
 $(top_srcdir)/lib/trigger_cxx_linking.cpp \
 /usr/include/stdc-predef.h

/usr/include/stdc-predef.h:

