# --- .deps/libTIC_la-tensor_redux_Cij_Div.Plo ---
tensor_redux_Cij_Div.o libTIC_la-tensor_redux_Cij_Div.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_Cij_Div.F

# --- .deps/libTIC_la-tensor_redux_CijLUde_1Mas_Div.Plo ---
tensor_redux_CijLUde_1Mas_Div.o \
 libTIC_la-tensor_redux_CijLUde_1Mas_Div.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUde_1Mas_Div.F

# --- .deps/libTIC_la-tensor_redux_CijLUde_1MasRank3_Div.Plo ---
tensor_redux_CijLUde_1MasRank3_Div.o \
 libTIC_la-tensor_redux_CijLUde_1MasRank3_Div.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUde_1MasRank3_Div.F

# --- .deps/libTIC_la-tensor_redux_CijLUde_1MasRank3.Plo ---
tensor_redux_CijLUde_1MasRank3.o \
 libTIC_la-tensor_redux_CijLUde_1MasRank3.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUde_1MasRank3.F

# --- .deps/libTIC_la-tensor_redux_CijLUdeRank3_Div.Plo ---
tensor_redux_CijLUdeRank3_Div.o \
 libTIC_la-tensor_redux_CijLUdeRank3_Div.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUdeRank3_Div.F

# --- .deps/libTIC_la-tensor_redux_CijLUde_Rank3_G_Div.Plo ---
tensor_redux_CijLUde_Rank3_G_Div.o \
 libTIC_la-tensor_redux_CijLUde_Rank3_G_Div.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUde_Rank3_G_Div.F

# --- .deps/libTIC_la-tensor_redux_CijLUde_Rank3_G.Plo ---
tensor_redux_CijLUde_Rank3_G.o libTIC_la-tensor_redux_CijLUde_Rank3_G.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUde_Rank3_G.F

# --- .deps/libTIC_la-tensor_redux_CijLUdeRank3.Plo ---
tensor_redux_CijLUdeRank3.o libTIC_la-tensor_redux_CijLUdeRank3.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUdeRank3.F

# --- .deps/libTIC_la-tensor_redux_CijLUdeRank4_G_Div.Plo ---
tensor_redux_CijLUdeRank4_G_Div.o \
 libTIC_la-tensor_redux_CijLUdeRank4_G_Div.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUdeRank4_G_Div.F

# --- .deps/libTIC_la-tensor_redux_CijLUdeRank4_G.Plo ---
tensor_redux_CijLUdeRank4_G.o libTIC_la-tensor_redux_CijLUdeRank4_G.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUdeRank4_G.F

# --- .deps/libTIC_la-tensor_redux_CijLUdeRank4_G_QUAD.Plo ---
tensor_redux_CijLUdeRank4_G_QUAD.o \
 libTIC_la-tensor_redux_CijLUdeRank4_G_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_CijLUdeRank4_G_QUAD.F

# --- .deps/libTIC_la-tensor_redux_Cij_new_Re_Com_1Mas.Plo ---
tensor_redux_Cij_new_Re_Com_1Mas.o \
 libTIC_la-tensor_redux_Cij_new_Re_Com_1Mas.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_Cij_new_Re_Com_1Mas.F \
 ../../../include/VBFNLO/utilities/global.inc

../../../include/VBFNLO/utilities/global.inc:

# --- .deps/libTIC_la-tensor_redux_Cij_new_Re_Com.Plo ---
tensor_redux_Cij_new_Re_Com.o libTIC_la-tensor_redux_Cij_new_Re_Com.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_Cij_new_Re_Com.F

# --- .deps/libTIC_la-tensor_redux_Cij_new_Re_Com_QUAD.Plo ---
tensor_redux_Cij_new_Re_Com_QUAD.o \
 libTIC_la-tensor_redux_Cij_new_Re_Com_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_Cij_new_Re_Com_QUAD.F

# --- .deps/libTIC_la-tensor_redux_Cij.Plo ---
tensor_redux_Cij.o libTIC_la-tensor_redux_Cij.lo: \
 $(top_srcdir)/loops/TenRed/C/tensor_redux_Cij.F

