# --- .deps/libvvj_la-ggWWg.Plo ---
ggWWg.o libvvj_la-ggWWg.lo: \
 $(top_srcdir)/amplitudes/vvj/ggWWg.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc \
 ../../include/VBFNLO/loops/Utilities/GaugeTest.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

../../include/VBFNLO/loops/Utilities/GaugeTest.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-ggZZg.Plo ---
ggZZg.o libvvj_la-ggZZg.lo: \
 $(top_srcdir)/amplitudes/vvj/ggZZg.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/koppln.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/loops/Utilities/GaugeTest.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/koppln.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/loops/Utilities/GaugeTest.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-leptens.Plo ---
leptens.o libvvj_la-leptens.lo: \
 $(top_srcdir)/amplitudes/vvj/leptens.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensorlep.inc \
 ../../include/VBFNLO/utilities/an_couplings.inc \
 ../../include/VBFNLO/utilities/mssm.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensorlep.inc:

../../include/VBFNLO/utilities/an_couplings.inc:

../../include/VBFNLO/utilities/mssm.inc:

# --- .deps/libvvj_la-m2s_qqVVj2.Plo ---
m2s_qqVVj2.o libvvj_la-m2s_qqVVj2.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqVVj2.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/kkcoupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/kkcoupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-m2s_qqVVjj.Plo ---
m2s_qqVVjj.o libvvj_la-m2s_qqVVjj.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqVVjj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-m2s_qqwmagj.Plo ---
m2s_qqwmagj.o libvvj_la-m2s_qqwmagj.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwmagj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensorlep.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensorlep.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-m2s_qqwmag.Plo ---
m2s_qqwmag.o libvvj_la-m2s_qqwmag.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwmag.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

# --- .deps/libvvj_la-m2s_qqwmagvirt.Plo ---
m2s_qqwmagvirt.o libvvj_la-m2s_qqwmagvirt.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwmagvirt.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvvj_la-m2s_qqwmzgj.Plo ---
m2s_qqwmzgj.o libvvj_la-m2s_qqwmzgj.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwmzgj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensorlep.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensorlep.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libvvj_la-m2s_qqwmzg.Plo ---
m2s_qqwmzg.o libvvj_la-m2s_qqwmzg.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwmzg.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

# --- .deps/libvvj_la-m2s_qqwmzgvirt.Plo ---
m2s_qqwmzgvirt.o libvvj_la-m2s_qqwmzgvirt.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwmzgvirt.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

# --- .deps/libvvj_la-m2s_qqwpagj.Plo ---
m2s_qqwpagj.o libvvj_la-m2s_qqwpagj.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwpagj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensorlep.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensorlep.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libvvj_la-m2s_qqwpag.Plo ---
m2s_qqwpag.o libvvj_la-m2s_qqwpag.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwpag.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

# --- .deps/libvvj_la-m2s_qqwpagvirt.Plo ---
m2s_qqwpagvirt.o libvvj_la-m2s_qqwpagvirt.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwpagvirt.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libvvj_la-m2s_qqwpzgj.Plo ---
m2s_qqwpzgj.o libvvj_la-m2s_qqwpzgj.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwpzgj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensorlep.inc \
 ../../include/VBFNLO/utilities/lha.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensorlep.inc:

../../include/VBFNLO/utilities/lha.inc:

# --- .deps/libvvj_la-m2s_qqwpzg.Plo ---
m2s_qqwpzg.o libvvj_la-m2s_qqwpzg.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwpzg.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/globalvars.mod:

# --- .deps/libvvj_la-m2s_qqwpzgvirt.Plo ---
m2s_qqwpzgvirt.o libvvj_la-m2s_qqwpzgvirt.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqwpzgvirt.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/genps.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/genps.inc:

# --- .deps/libvvj_la-m2s_qqZZj2.Plo ---
m2s_qqZZj2.o libvvj_la-m2s_qqZZj2.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqZZj2.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 ../../include/VBFNLO/utilities/kkcoupl.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

../../include/VBFNLO/utilities/kkcoupl.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-m2s_qqZZjj.Plo ---
m2s_qqZZjj.o libvvj_la-m2s_qqZZjj.lo: \
 $(top_srcdir)/amplitudes/vvj/m2s_qqZZjj.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_ddWWdd.Plo ---
mg2_ddWWdd.o libvvj_la-mg2_ddWWdd.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_ddWWdd.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_ddWWgg.Plo ---
mg2_ddWWgg.o libvvj_la-mg2_ddWWgg.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_ddWWgg.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_ddZZdd.Plo ---
mg2_ddZZdd.o libvvj_la-mg2_ddZZdd.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_ddZZdd.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_ddZZgg.Plo ---
mg2_ddZZgg.o libvvj_la-mg2_ddZZgg.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_ddZZgg.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_duWWdu.Plo ---
mg2_duWWdu.o libvvj_la-mg2_duWWdu.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_duWWdu.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_duZZdu.Plo ---
mg2_duZZdu.o libvvj_la-mg2_duZZdu.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_duZZdu.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_udWWud.Plo ---
mg2_udWWud.o libvvj_la-mg2_udWWud.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_udWWud.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_udZZud.Plo ---
mg2_udZZud.o libvvj_la-mg2_udZZud.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_udZZud.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_uuWWgg.Plo ---
mg2_uuWWgg.o libvvj_la-mg2_uuWWgg.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_uuWWgg.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_uuWWuu.Plo ---
mg2_uuWWuu.o libvvj_la-mg2_uuWWuu.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_uuWWuu.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_uuZZgg.Plo ---
mg2_uuZZgg.o libvvj_la-mg2_uuZZgg.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_uuZZgg.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-mg2_uuZZuu.Plo ---
mg2_uuZZuu.o libvvj_la-mg2_uuZZuu.lo: \
 $(top_srcdir)/amplitudes/vvj/mg2_uuZZuu.F \
 $(top_srcdir)/amplitudes/vvj/genps.inc \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

$(top_srcdir)/amplitudes/vvj/genps.inc:

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-qqVVgg.Plo ---
qqVVgg.o libvvj_la-qqVVgg.lo: \
 $(top_srcdir)/amplitudes/vvj/qqVVgg.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-qqVVqq.Plo ---
qqVVqq.o libvvj_la-qqVVqq.lo: \
 $(top_srcdir)/amplitudes/vvj/qqVVqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-qqWWj_curr.Plo ---
qqWWj_curr.o libvvj_la-qqWWj_curr.lo: \
 $(top_srcdir)/amplitudes/vvj/qqWWj_curr.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-qqZZgg.Plo ---
qqZZgg.o libvvj_la-qqZZgg.lo: \
 $(top_srcdir)/amplitudes/vvj/qqZZgg.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-qqZZj_curr.Plo ---
qqZZj_curr.o libvvj_la-qqZZj_curr.lo: \
 $(top_srcdir)/amplitudes/vvj/qqZZj_curr.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

# --- .deps/libvvj_la-qqZZqq.Plo ---
qqZZqq.o libvvj_la-qqZZqq.lo: \
 $(top_srcdir)/amplitudes/vvj/qqZZqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/coupl.inc \
 $(top_srcdir)/amplitudes/vvj/tensor.inc \
 $(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/coupl.inc:

$(top_srcdir)/amplitudes/vvj/tensor.inc:

$(top_srcdir)/amplitudes/vvj/../diboson/tensor.inc:

