# --- .deps/FFini.Po ---
FFini.o FFini.o: \
 $(top_srcdir)/src/FFini.F90 \
 ../include/globalvars.mod ../include/globalvars.mod

../include/globalvars.mod:

../include/globalvars.mod:

# --- .deps/vbfnlo-LTools.Po ---
LTools.o vbfnlo-LTools.o: LTools.F \
 $(LOOPTOOLS_DIR)/include/looptools.h

$(LOOPTOOLS_DIR)/include/looptools.h:

# --- .deps/vbfnlo_main.Po ---
vbfnlo_main.o vbfnlo_main.o: \
 $(top_srcdir)/src/vbfnlo_main.F90 \
 ../include/vbfnlo_main.mod ../include/globalvars.mod \
 ../include/cmd_args.mod

../include/vbfnlo_main.mod:

../include/globalvars.mod:

../include/cmd_args.mod:

# --- .deps/vbfnlo_olpread-FFini-dummy.Po ---
FFini-dummy.o vbfnlo_olpread-FFini-dummy.o: \
 $(top_srcdir)/src/FFini-dummy.F

# --- .deps/vbfnlo_olpread-LTools-dummy.Po ---
LTools-dummy.o vbfnlo_olpread-LTools-dummy.o: \
 $(top_srcdir)/src/LTools-dummy.F

# --- .deps/vbfnlo_olpread.Po ---
vbfnlo_olpread.o: \
 $(top_srcdir)/src/vbfnlo_olpread.cxx \
 /usr/include/stdc-predef.h /usr/include/c++/4.8/iostream \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/c++config.h \
 /usr/include/bits/wordsize.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/os_defines.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h /usr/include/gnu/stubs-64.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/cpu_defines.h \
 /usr/include/c++/4.8/ostream /usr/include/c++/4.8/ios \
 /usr/include/c++/4.8/iosfwd /usr/include/c++/4.8/bits/stringfwd.h \
 /usr/include/c++/4.8/bits/memoryfwd.h \
 /usr/include/c++/4.8/bits/postypes.h /usr/include/c++/4.8/cwchar \
 /usr/include/wchar.h /usr/include/stdio.h \
 /usr/lib64/gcc/x86_64-suse-linux/4.8/include/stdarg.h \
 /usr/include/bits/wchar.h \
 /usr/lib64/gcc/x86_64-suse-linux/4.8/include/stddef.h \
 /usr/include/xlocale.h /usr/include/c++/4.8/exception \
 /usr/include/c++/4.8/bits/atomic_lockfree_defines.h \
 /usr/include/c++/4.8/bits/char_traits.h \
 /usr/include/c++/4.8/bits/stl_algobase.h \
 /usr/include/c++/4.8/bits/functexcept.h \
 /usr/include/c++/4.8/bits/exception_defines.h \
 /usr/include/c++/4.8/bits/cpp_type_traits.h \
 /usr/include/c++/4.8/ext/type_traits.h \
 /usr/include/c++/4.8/ext/numeric_traits.h \
 /usr/include/c++/4.8/bits/stl_pair.h /usr/include/c++/4.8/bits/move.h \
 /usr/include/c++/4.8/bits/concept_check.h \
 /usr/include/c++/4.8/bits/stl_iterator_base_types.h \
 /usr/include/c++/4.8/bits/stl_iterator_base_funcs.h \
 /usr/include/c++/4.8/debug/debug.h \
 /usr/include/c++/4.8/bits/stl_iterator.h \
 /usr/include/c++/4.8/bits/localefwd.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/c++locale.h \
 /usr/include/c++/4.8/clocale /usr/include/locale.h \
 /usr/include/bits/locale.h /usr/include/c++/4.8/cctype \
 /usr/include/ctype.h /usr/include/bits/types.h \
 /usr/include/bits/typesizes.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/bits/byteswap.h \
 /usr/include/bits/byteswap-16.h /usr/include/c++/4.8/bits/ios_base.h \
 /usr/include/c++/4.8/ext/atomicity.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/gthr.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/gthr-default.h \
 /usr/include/pthread.h /usr/include/sched.h /usr/include/time.h \
 /usr/include/bits/sched.h /usr/include/bits/time.h \
 /usr/include/bits/timex.h /usr/include/bits/pthreadtypes.h \
 /usr/include/bits/setjmp.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/atomic_word.h \
 /usr/include/c++/4.8/bits/locale_classes.h /usr/include/c++/4.8/string \
 /usr/include/c++/4.8/bits/allocator.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/c++allocator.h \
 /usr/include/c++/4.8/ext/new_allocator.h /usr/include/c++/4.8/new \
 /usr/include/c++/4.8/bits/ostream_insert.h \
 /usr/include/c++/4.8/bits/cxxabi_forced.h \
 /usr/include/c++/4.8/bits/stl_function.h \
 /usr/include/c++/4.8/backward/binders.h \
 /usr/include/c++/4.8/bits/range_access.h \
 /usr/include/c++/4.8/bits/basic_string.h \
 /usr/include/c++/4.8/bits/basic_string.tcc \
 /usr/include/c++/4.8/bits/locale_classes.tcc \
 /usr/include/c++/4.8/streambuf /usr/include/c++/4.8/bits/streambuf.tcc \
 /usr/include/c++/4.8/bits/basic_ios.h \
 /usr/include/c++/4.8/bits/locale_facets.h /usr/include/c++/4.8/cwctype \
 /usr/include/wctype.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/ctype_base.h \
 /usr/include/c++/4.8/bits/streambuf_iterator.h \
 /usr/include/c++/4.8/x86_64-suse-linux/bits/ctype_inline.h \
 /usr/include/c++/4.8/bits/locale_facets.tcc \
 /usr/include/c++/4.8/bits/basic_ios.tcc \
 /usr/include/c++/4.8/bits/ostream.tcc /usr/include/c++/4.8/istream \
 /usr/include/c++/4.8/bits/istream.tcc /usr/include/c++/4.8/cstring \
 /usr/include/string.h ../include/VBFNLO/utilities/BLHAinterface.h

/usr/include/stdc-predef.h:

/usr/include/c++/4.8/iostream:

/usr/include/c++/4.8/x86_64-suse-linux/bits/c++config.h:

/usr/include/bits/wordsize.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/os_defines.h:

/usr/include/features.h:

/usr/include/sys/cdefs.h:

/usr/include/gnu/stubs.h:

/usr/include/gnu/stubs-64.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/cpu_defines.h:

/usr/include/c++/4.8/ostream:

/usr/include/c++/4.8/ios:

/usr/include/c++/4.8/iosfwd:

/usr/include/c++/4.8/bits/stringfwd.h:

/usr/include/c++/4.8/bits/memoryfwd.h:

/usr/include/c++/4.8/bits/postypes.h:

/usr/include/c++/4.8/cwchar:

/usr/include/wchar.h:

/usr/include/stdio.h:

/usr/lib64/gcc/x86_64-suse-linux/4.8/include/stdarg.h:

/usr/include/bits/wchar.h:

/usr/lib64/gcc/x86_64-suse-linux/4.8/include/stddef.h:

/usr/include/xlocale.h:

/usr/include/c++/4.8/exception:

/usr/include/c++/4.8/bits/atomic_lockfree_defines.h:

/usr/include/c++/4.8/bits/char_traits.h:

/usr/include/c++/4.8/bits/stl_algobase.h:

/usr/include/c++/4.8/bits/functexcept.h:

/usr/include/c++/4.8/bits/exception_defines.h:

/usr/include/c++/4.8/bits/cpp_type_traits.h:

/usr/include/c++/4.8/ext/type_traits.h:

/usr/include/c++/4.8/ext/numeric_traits.h:

/usr/include/c++/4.8/bits/stl_pair.h:

/usr/include/c++/4.8/bits/move.h:

/usr/include/c++/4.8/bits/concept_check.h:

/usr/include/c++/4.8/bits/stl_iterator_base_types.h:

/usr/include/c++/4.8/bits/stl_iterator_base_funcs.h:

/usr/include/c++/4.8/debug/debug.h:

/usr/include/c++/4.8/bits/stl_iterator.h:

/usr/include/c++/4.8/bits/localefwd.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/c++locale.h:

/usr/include/c++/4.8/clocale:

/usr/include/locale.h:

/usr/include/bits/locale.h:

/usr/include/c++/4.8/cctype:

/usr/include/ctype.h:

/usr/include/bits/types.h:

/usr/include/bits/typesizes.h:

/usr/include/endian.h:

/usr/include/bits/endian.h:

/usr/include/bits/byteswap.h:

/usr/include/bits/byteswap-16.h:

/usr/include/c++/4.8/bits/ios_base.h:

/usr/include/c++/4.8/ext/atomicity.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/gthr.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/gthr-default.h:

/usr/include/pthread.h:

/usr/include/sched.h:

/usr/include/time.h:

/usr/include/bits/sched.h:

/usr/include/bits/time.h:

/usr/include/bits/timex.h:

/usr/include/bits/pthreadtypes.h:

/usr/include/bits/setjmp.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/atomic_word.h:

/usr/include/c++/4.8/bits/locale_classes.h:

/usr/include/c++/4.8/string:

/usr/include/c++/4.8/bits/allocator.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/c++allocator.h:

/usr/include/c++/4.8/ext/new_allocator.h:

/usr/include/c++/4.8/new:

/usr/include/c++/4.8/bits/ostream_insert.h:

/usr/include/c++/4.8/bits/cxxabi_forced.h:

/usr/include/c++/4.8/bits/stl_function.h:

/usr/include/c++/4.8/backward/binders.h:

/usr/include/c++/4.8/bits/range_access.h:

/usr/include/c++/4.8/bits/basic_string.h:

/usr/include/c++/4.8/bits/basic_string.tcc:

/usr/include/c++/4.8/bits/locale_classes.tcc:

/usr/include/c++/4.8/streambuf:

/usr/include/c++/4.8/bits/streambuf.tcc:

/usr/include/c++/4.8/bits/basic_ios.h:

/usr/include/c++/4.8/bits/locale_facets.h:

/usr/include/c++/4.8/cwctype:

/usr/include/wctype.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/ctype_base.h:

/usr/include/c++/4.8/bits/streambuf_iterator.h:

/usr/include/c++/4.8/x86_64-suse-linux/bits/ctype_inline.h:

/usr/include/c++/4.8/bits/locale_facets.tcc:

/usr/include/c++/4.8/bits/basic_ios.tcc:

/usr/include/c++/4.8/bits/ostream.tcc:

/usr/include/c++/4.8/istream:

/usr/include/c++/4.8/bits/istream.tcc:

/usr/include/c++/4.8/cstring:

/usr/include/string.h:

../include/VBFNLO/utilities/BLHAinterface.h:

