# --- .deps/libDiagramsBoxL_la-boxlineABEDiv.Plo ---
boxlineABEDiv.o libDiagramsBoxL_la-boxlineABEDiv.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineABEDiv.F

# --- .deps/libDiagramsBoxL_la-boxlineABE.Plo ---
boxlineABE.o libDiagramsBoxL_la-boxlineABE.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineABE.F

# --- .deps/libDiagramsBoxL_la-boxlineABE_QUAD.Plo ---
boxlineABE_QUAD.o libDiagramsBoxL_la-boxlineABE_QUAD.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineABE_QUAD.F

# --- .deps/libDiagramsBoxL_la-boxlineABETotal.Plo ---
boxlineABETotal.o libDiagramsBoxL_la-boxlineABETotal.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineABETotal.F

# --- .deps/libDiagramsBoxL_la-boxlineNoAbeDiv.Plo ---
boxlineNoAbeDiv.o libDiagramsBoxL_la-boxlineNoAbeDiv.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineNoAbeDiv.F

# --- .deps/libDiagramsBoxL_la-boxlineNoAbe_pDiv.Plo ---
boxlineNoAbe_pDiv.o libDiagramsBoxL_la-boxlineNoAbe_pDiv.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineNoAbe_pDiv.F

# --- .deps/libDiagramsBoxL_la-boxlineNoAbe.Plo ---
boxlineNoAbe.o libDiagramsBoxL_la-boxlineNoAbe.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineNoAbe.F

# --- .deps/libDiagramsBoxL_la-boxlineNoAbe_p.Plo ---
boxlineNoAbe_p.o libDiagramsBoxL_la-boxlineNoAbe_p.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineNoAbe_p.F

# --- .deps/libDiagramsBoxL_la-boxlineNoAbe_QUAD.Plo ---
boxlineNoAbe_QUAD.o libDiagramsBoxL_la-boxlineNoAbe_QUAD.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineNoAbe_QUAD.F

# --- .deps/libDiagramsBoxL_la-boxlineNoAbeTotal.Plo ---
boxlineNoAbeTotal.o libDiagramsBoxL_la-boxlineNoAbeTotal.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineNoAbeTotal.F

# --- .deps/libDiagramsBoxL_la-boxlineNoAbeTotal_p.Plo ---
boxlineNoAbeTotal_p.o libDiagramsBoxL_la-boxlineNoAbeTotal_p.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxlineNoAbeTotal_p.F

# --- .deps/libDiagramsBoxL_la-boxline.Plo ---
boxline.o libDiagramsBoxL_la-boxline.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxline.F

# --- .deps/libDiagramsBoxL_la-boxline_QUAD.Plo ---
boxline_QUAD.o libDiagramsBoxL_la-boxline_QUAD.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/boxline_QUAD.F

# --- .deps/libDiagramsBoxL_la-XDGetM0_QUAD_Dble.Plo ---
XDGetM0_QUAD_Dble.o libDiagramsBoxL_la-XDGetM0_QUAD_Dble.lo: \
 $(top_srcdir)/loops/Diagrams/Boxline/XDGetM0_QUAD_Dble.F

