# --- .deps/libTIF_la-tensor_redux_Fij_new_Re_Com.Plo ---
tensor_redux_Fij_new_Re_Com.o libTIF_la-tensor_redux_Fij_new_Re_Com.lo: \
 $(top_srcdir)/loops/TenRed/F/tensor_redux_Fij_new_Re_Com.F

# --- .deps/libTIF_la-tensor_redux_Fij_new_Re_Com_QUAD.Plo ---
tensor_redux_Fij_new_Re_Com_QUAD.o \
 libTIF_la-tensor_redux_Fij_new_Re_Com_QUAD.lo: \
 $(top_srcdir)/loops/TenRed/F/tensor_redux_Fij_new_Re_Com_QUAD.F

