# --- .deps/libhjjj_la-coeff.Plo ---
coeff.o libhjjj_la-coeff.lo: \
 $(top_srcdir)/amplitudes/hjjj/coeff.F

# --- .deps/libhjjj_la-dc_usbbh.Plo ---
dc_usbbh.o libhjjj_la-dc_usbbh.lo: \
 $(top_srcdir)/amplitudes/hjjj/dc_usbbh.F \
 $(top_srcdir)/amplitudes/hjjj/genps.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/hjjj/genps.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libhjjj_la-dipolesub.Plo ---
dipolesub.o libhjjj_la-dipolesub.lo: \
 $(top_srcdir)/amplitudes/hjjj/dipolesub.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libhjjj_la-dipsub.Plo ---
dipsub.o libhjjj_la-dipsub.lo: \
 $(top_srcdir)/amplitudes/hjjj/dipsub.F \
 ../../include/VBFNLO/utilities/global.inc \
 $(top_srcdir)/amplitudes/hjjj/color.inc

../../include/VBFNLO/utilities/global.inc:

$(top_srcdir)/amplitudes/hjjj/color.inc:

# --- .deps/libhjjj_la-hjjj_amp_aux.Plo ---
hjjj_amp_aux.o libhjjj_la-hjjj_amp_aux.lo: \
 $(top_srcdir)/amplitudes/hjjj/hjjj_amp_aux.F \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libhjjj_la-m2s_qqh3j.Plo ---
m2s_qqh3j.o libhjjj_la-m2s_qqh3j.lo: \
 $(top_srcdir)/amplitudes/hjjj/m2s_qqh3j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/process.inc \
 $(top_srcdir)/amplitudes/hjjj/color.inc \
 ../../include/globalvars.mod ../../include/vbfnlo_higgsto.mod \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/scales.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/process.inc:

$(top_srcdir)/amplitudes/hjjj/color.inc:

../../include/globalvars.mod:

../../include/vbfnlo_higgsto.mod:

../../include/globalvars.mod:

# --- .deps/libhjjj_la-m2s_qqh4j.Plo ---
m2s_qqh4j.o libhjjj_la-m2s_qqh4j.lo: \
 $(top_srcdir)/amplitudes/hjjj/m2s_qqh4j.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 ../../include/VBFNLO/utilities/process.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/hjjj/color.inc \
 ../../include/vbfnlo_higgsto.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

../../include/VBFNLO/utilities/process.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/hjjj/color.inc:

../../include/vbfnlo_higgsto.mod:

# --- .deps/libhjjj_la-qqh4qcc_sub.Plo ---
qqh4qcc_sub.o libhjjj_la-qqh4qcc_sub.lo: \
 $(top_srcdir)/amplitudes/hjjj/qqh4qcc_sub.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/hjjj/color.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/hjjj/color.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libhjjj_la-qqh4q_mg.Plo ---
qqh4q_mg.o libhjjj_la-qqh4q_mg.lo: \
 $(top_srcdir)/amplitudes/hjjj/qqh4q_mg.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/mssm.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/mssm.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libhjjj_la-qqh4q_sub.Plo ---
qqh4q_sub.o libhjjj_la-qqh4q_sub.lo: \
 $(top_srcdir)/amplitudes/hjjj/qqh4q_sub.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/lha.inc \
 $(top_srcdir)/amplitudes/hjjj/color.inc \
 ../../include/VBFNLO/utilities/scales.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/lha.inc:

$(top_srcdir)/amplitudes/hjjj/color.inc:

../../include/VBFNLO/utilities/scales.inc:

# --- .deps/libhjjj_la-qqhqqgg_cc.Plo ---
qqhqqgg_cc.o libhjjj_la-qqhqqgg_cc.lo: \
 $(top_srcdir)/amplitudes/hjjj/qqhqqgg_cc.F \
 $(top_srcdir)/amplitudes/hjjj/genps.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/hjjj/genps.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libhjjj_la-qqhqqgg_mgfast.Plo ---
qqhqqgg_mgfast.o libhjjj_la-qqhqqgg_mgfast.lo: \
 $(top_srcdir)/amplitudes/hjjj/qqhqqgg_mgfast.F \
 $(top_srcdir)/amplitudes/hjjj/genps.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/hjjj/genps.inc:

../../include/VBFNLO/utilities/coupl.inc:

# --- .deps/libhjjj_la-qqhqqgg_mg.Plo ---
qqhqqgg_mg.o libhjjj_la-qqhqqgg_mg.lo: \
 $(top_srcdir)/amplitudes/hjjj/qqhqqgg_mg.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/mssm.inc \
 ../../include/VBFNLO/utilities/koppln.inc

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/mssm.inc:

../../include/VBFNLO/utilities/koppln.inc:

# --- .deps/libhjjj_la-qqhqq.Plo ---
qqhqq.o libhjjj_la-qqhqq.lo: \
 $(top_srcdir)/amplitudes/hjjj/qqhqq.F \
 ../../include/VBFNLO/utilities/global.inc \
 ../../include/VBFNLO/utilities/BLHAhelper.inc \
 ../../include/VBFNLO/utilities/mssm.inc \
 ../../include/VBFNLO/utilities/koppln.inc \
 ../../include/VBFNLO/utilities/scales.inc \
 $(top_srcdir)/amplitudes/hjjj/color.inc \
 ../../include/globalvars.mod

../../include/VBFNLO/utilities/global.inc:

../../include/VBFNLO/utilities/BLHAhelper.inc:

../../include/VBFNLO/utilities/mssm.inc:

../../include/VBFNLO/utilities/koppln.inc:

../../include/VBFNLO/utilities/scales.inc:

$(top_srcdir)/amplitudes/hjjj/color.inc:

../../include/globalvars.mod:

# --- .deps/libhjjj_la-us_usbbh.Plo ---
us_usbbh.o libhjjj_la-us_usbbh.lo: \
 $(top_srcdir)/amplitudes/hjjj/us_usbbh.F \
 $(top_srcdir)/amplitudes/hjjj/genps.inc \
 ../../include/VBFNLO/utilities/coupl.inc

$(top_srcdir)/amplitudes/hjjj/genps.inc:

../../include/VBFNLO/utilities/coupl.inc:

